//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelControls
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Button Button1;

        protected global::System.Web.UI.WebControls.Panel Panel1;

        protected global::System.Web.UI.WebControls.Image Image1;

        protected global::System.Web.UI.WebControls.Label Label1;

        protected global::System.Web.UI.WebControls.HyperLink HyperLink1;

        protected global::System.Web.UI.WebControls.Button Button2;
    }
}